pipeline:
  identifier: Build_ci_java_jhttp_lab_1746915873052
  name: Build ci-java-jhttp-lab
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.github_ci_connector
        repoName: ci-java-jhttp-lab
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  names: Run Unit Tests
                  type: Run
                  identifier: run_tests
                  name: Build Java App
                  spec:
                    shell: Sh
                    image: maven:3.8-jdk-11
                    command: mvn clean test
              - step:
                  name: Package App
                  identifier: package_app
                  type: Run
                  spec:
                    shell: Sh
                    image: maven:3.8-jdk-11
                    command: mvn package -DskipTests
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: esglusto/ci-java-jhttp
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
